language: ruby
script: "rake travis:ci"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - 2.2.1
  - jruby-19mode
gemfile:
  - gemfiles/cucumber.1.3.gemfile
  - gemfiles/cucumber.2.4.gemfile
  - gemfiles/latest.gemfile
  - gemfiles/rspec.3.0.gemfile
  - gemfiles/spinach.0.8.gemfile
